### ISSUE TITLE
How do I run the bot myself?

### ISSUE THREAD

**Issue by AleksandrPe** [faizan12123/ChatZon-ChatGPT-Discord-Bot#1]
Good afternoon, you will not be posting the source code of this project? I would like to try to run it in mine and see the code.

**Comment by faizanH** [comment]
Hello @AleksandrPe , Unfortunately, I will not be posting the source code for this project, but you can still add the bot to your server by following the link provided in the readMe. Please let me know if you have any other questions or concerns!
